# Generated by Django 5.0.9 on 2024-10-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.IntegerField(max_length=2),
        ),
    ]
