# Generated by Django 5.0.3 on 2024-10-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_question_questiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('if-else', 'if-else'), ('for-loop', 'for-loop'), ('while-loop', 'while-loop'), ('function', 'function'), ('list', 'list'), ('dictionary', 'dictionary'), ('string', 'string'), ('file', 'file'), ('exception', 'exception')], max_length=20)),
            ],
        ),
    ]
