# Generated by Django 5.0.3 on 2024-10-24 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_questionassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionassignment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='questioncategory',
            name='title',
        ),
        migrations.AddField(
            model_name='questionassignment',
            name='question_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.questiondata'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='question_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.questiondata'),
        ),
    ]
