# Generated by Django 5.0.3 on 2024-10-24 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_questionassignment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionassignment',
            name='question_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.questiondata'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='question_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.questiondata'),
        ),
    ]
