# Generated by Django 5.0.3 on 2024-10-24 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_questionassignment_question_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionassignment',
            name='question_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.questiondata'),
        ),
    ]
