# Generated by Django 5.0.3 on 2024-10-24 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_questionassignment_question_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='question_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.questiondata'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='type',
            field=models.CharField(blank=True, choices=[('if-else', 'if-else'), ('for-loop', 'for-loop'), ('while-loop', 'while-loop'), ('function', 'function'), ('list', 'list'), ('dictionary', 'dictionary'), ('string', 'string'), ('file', 'file'), ('exception', 'exception')], max_length=20, null=True),
        ),
    ]
