# Generated by Django 5.0.3 on 2024-10-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_questionassignment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='type',
            field=models.CharField(choices=[('if-else', 'if-else'), ('for-loop', 'for-loop'), ('while-loop', 'while-loop'), ('function', 'function'), ('list', 'list'), ('dictionary', 'dictionary'), ('string', 'string'), ('file', 'file'), ('exception', 'exception')], max_length=20),
        ),
    ]
