export const scaleFactor = 2.3;

export const dialogueData = {
  House1: `House1.`,
  House2: `House2.`,
  House3: `House3.`,
  House4: `House4.`,
  House5: `House5.`,
  City_House1: `City_House1.`,
  City_House2: `City_House2.`,
  Desert: `Desert.`,
  bulletin1: `遊戲介紹 <a href="https://www.canva.com/design/DAGhD35axGQ/sRSUJf3-Vb_1N7qLBBOsZw/edit?utm_content=DAGhD35axGQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton" target="_blank" style="text-decoration: none">連結</a> `,
  bulletin2: `第一單元「基礎概念」<a href="https://www.canva.com/design/DAGhECrGS9M/eDmQoSKl4sHcWr1by3RzdA/edit?utm_content=DAGhECrGS9M&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton" target="_blank" style="text-decoration: none">連結</a> `,
  bulletin3: `第二單元「相等性」<a href="https://www.canva.com/design/DAGhYhO-kMY/DRN3m9PE7Nqo_iTnppe9mg/edit?utm_content=DAGhYhO-kMY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton" target="_blank" style="text-decoration: none">連結</a> `,
  bulletin4: `第三單元「迴圈」<a href="https://www.canva.com/design/DAGiYZlgG2g/ALJ2kqqL3LbcYN8Nu13Hiw/edit?utm_content=DAGiYZlgG2g&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton" target="_blank" style="text-decoration: none">連結</a> `,
  bulletin5: `第四單元「邏輯控制」<a href="https://www.canva.com/design/DAGiYQVFY6E/qFEA8PtjpCTKHKcgxxRldg/edit?utm_content=DAGiYQVFY6E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton" target="_blank" style="text-decoration: none">連結</a> `,
  King: `King. I like to play chess with him.`,
  Nan: `Nan`,
  npc_1: `npc_1.`,
  npc_2: `npc_2.`,
  npc_3: `npc_3.`,
  npc_4: `npc_4.`,
  npc_5: `npc_5.`,
  crack_blue_1: `crack_blue_1.`,
  crack_red_1: `crack_red_2.`,
  crack_blue_2: `crack_blue_2.`,
  crack_red_2: `crack_red_2.`,
  crack_blue_3: `crack_blue_3.`,
  crack_red_3: `crack_red_3.`,
  crack_blue_4: `crack_blue_4.`,
  crack_red_4: `crack_red_4.`,
  big_crack: `big_crack.`,
};
