# Generated by Django 4.2.16 on 2025-04-10 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('clear', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Cname', models.CharField(max_length=100)),
                ('Ename', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=300)),
                ('background', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_content', models.CharField(max_length=500)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('used', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.character')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('clear', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level')),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener', to='games.character')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='games.character')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('answer', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=20)),
                ('correct', models.BooleanField(default=False)),
                ('map_object_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level')),
                ('listener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.character')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBlue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('map_object_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level')),
                ('listener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.character')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('answer', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=20)),
                ('correct', models.BooleanField(default=False)),
                ('map_object_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level')),
                ('listener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.character')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('red_crack', '紅色裂縫'), ('blue_crack', '藍色裂縫'), ('big_crack', '大裂縫')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('cleared', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_big', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.questionbig')),
                ('question_blue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.questionblue')),
                ('question_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.questionred')),
            ],
        ),
        migrations.CreateModel(
            name='UserLineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.line')),
            ],
        ),
        migrations.CreateModel(
            name='UserLevelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level')),
            ],
        ),
        migrations.CreateModel(
            name='UserItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.item')),
            ],
        ),
        migrations.CreateModel(
            name='UserHintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.hint')),
            ],
        ),
        migrations.CreateModel(
            name='UserChapterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='questionred',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.questiontype'),
        ),
        migrations.AddField(
            model_name='questionblue',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.questiontype'),
        ),
        migrations.AddField(
            model_name='questionbig',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.questiontype'),
        ),
        migrations.AddField(
            model_name='hint',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level'),
        ),
        migrations.AddField(
            model_name='hint',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_listener', to='games.character'),
        ),
        migrations.AddField(
            model_name='hint',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_speaker', to='games.character'),
        ),
        migrations.CreateModel(
            name='ChapterFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.line')),
                ('question_big', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.questionbig')),
                ('question_blue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.questionblue')),
                ('question_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.questionred')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
