# Generated by Django 4.2.16 on 2025-03-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('clear', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Cname', models.CharField(max_length=100)),
                ('Ename', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=300)),
                ('background', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('clear', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('red_crack', '紅色裂縫'), ('blue_crack', '藍色裂縫')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('answer', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=20)),
                ('correct', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBlue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('content', models.CharField(max_length=300)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chapter')),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener', to='games.character')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='games.character')),
            ],
        ),
    ]
