# Generated by Django 4.2.16 on 2025-03-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='line_id',
        ),
    ]
