# Generated by Django 4.2.16 on 2025-03-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_chapterflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterflow',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='chapterflow',
            name='object_id',
        ),
        migrations.AddField(
            model_name='chapterflow',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.line'),
        ),
        migrations.AddField(
            model_name='chapterflow',
            name='question_blue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.questionblue'),
        ),
        migrations.AddField(
            model_name='chapterflow',
            name='question_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.questionred'),
        ),
    ]
