# Generated by Django 4.2.16 on 2025-03-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_chapterflow_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblue',
            name='listener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.character'),
        ),
        migrations.AddField(
            model_name='questionred',
            name='listener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.character'),
        ),
        migrations.AlterField(
            model_name='questionblue',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionred',
            name='question',
            field=models.TextField(),
        ),
    ]
