# Generated by Django 4.2.16 on 2025-03-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_userquestionrecord_userlinerecord_userlevelrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionrecord',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
